---
# Source: docker-compose/templates/main.yaml
version: "3.8"
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: snitzsh_db
    volumes:
      - "./volumes/postgres/data:/var/lib/postgresql/data"
      - "./volumes/postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql"
    labels:
      - "com.docker.compose.service=public"
      - "com.docker.compose.component-name=postgres"
      - "com.docker.compose.component-type=db"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin4:
    container_name: pgadmin4
    hostname: pgadmin4
    image: "dpage/pgadmin4:latest"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@snitzsh.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - "./volumes/pgadmin4:/var/lib/pgadmin"
    labels:
      - "com.docker.compose.service=public"
      - "com.docker.compose.component-name=pgadmin4"
      - "com.docker.compose.component-type=db-ui"
    expose:
      - '80'
    ports:
      - '5050:80'
    networks:
      - postgres
    depends_on:
      - postgres
  redis:
    container_name: redis
    hostname: redis
    image: "redis:latest"
    restart: always
    environment:
      REDIS_USERNAME: root
    volumes:
      - "./volumes/redis/data:/data"
    labels:
      - "com.docker.compose.service=public"
      - "com.docker.compose.component-name=redis"
      - "com.docker.compose.component-type=in-memory-data-storage"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    networks:
      - redis
  redisinsight:
    container_name: redisinsight
    hostname: redisinsight
    image: "redislabs/redisinsight:latest"
    restart: always
    environment: {}
    volumes:
      - "./volumes/redisinsight:/db"
    labels:
      - "com.docker.compose.service=public"
      - "com.docker.compose.component-name=redisinsight"
      - "com.docker.compose.component-type=in-memory-data-storage-ui"
    ports:
      - 5540:5540
    networks:
      - redis
    depends_on:
      - redis
volumes:
  apis-fastify:
    driver: local
  apis-rust:
    driver: local
  grafana:
    driver: local
  pgadmin4:
    driver: local
  postgres:
    driver: local
  redis:
    driver: local
  redisinsight:
    driver: local
  website-vue:
    driver: local
networks:
  redis:
    driver: bridge
  postgres:
    driver: bridge
