---
# Source: docker-compose/templates/main.yaml
name: platform
services:
  apis-snitzsh-main-rust:
    build:
      args:
        _WORKDIR: /app
        RUST_APP_PLATFORM_CLUSTER_NAME: dev
        RUST_APP_PLATFORM_CLUSTER_TYPE: local
        RUST_APP_PLATFORM_HOST: 0.0.0.0
        RUST_APP_PLATFORM_PORT: "3000"
        RUST_APP_PLATFORM_SCRIPT_TARGET: dev
      context: ../../../apis/snitzsh/main-rust
      dockerfile: Dockerfile
      target: dev-stage
    container_name: apis-snitzsh-main-rust
    depends_on: []
    environment: {}
    hostname: apis-snitzsh-main-rust
    image: apis-snitzsh-main-rust:latest
    labels:
    - com.docker.compose.software-type=private
    - com.docker.compose.component-name=apis
    - com.docker.compose.app-name=snitzsh
    - com.docker.compose.project-name=main-rust
    - com.docker.compose.service-name=apis-snitzsh-main-rust
    - com.docker.compose.platform=linux/arm64
    - com.docker.compose.docker-stage=dev-stage
    - com.docker.compose.target-script=dev
    platform: linux/arm64
    ports:
    - 3000:3000
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - ../../../apis/snitzsh/main-rust:/app
  uis-snitzsh-main-vue:
    build:
      args:
        _WORKDIR: /app
        VITE_APP_PLATFORM_CLUSTER_NAME: dev
        VITE_APP_PLATFORM_CLUSTER_TYPE: local
        VITE_APP_PLATFORM_HOST: 0.0.0.0
        VITE_APP_PLATFORM_PORT: "8080"
        VITE_APP_PLATFORM_SCRIPT_TARGET: dev
      context: ../../../uis/snitzsh/main-vue
      dockerfile: Dockerfile
      target: dev-stage
    container_name: uis-snitzsh-main-vue
    depends_on:
    - apis-snitzsh-main-rust
    environment: {}
    hostname: uis-snitzsh-main-vue
    image: uis-snitzsh-main-vue:latest
    labels:
    - com.docker.compose.software-type=private
    - com.docker.compose.component-name=uis
    - com.docker.compose.app-name=snitzsh
    - com.docker.compose.project-name=main-vue
    - com.docker.compose.service-name=uis-snitzsh-main-vue
    - com.docker.compose.platform=linux/arm64
    - com.docker.compose.docker-stage=dev-stage
    - com.docker.compose.target-script=dev
    platform: linux/arm64
    ports:
    - 8080:8080
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - ../../../uis/snitzsh/main-vue/src:/app/src
volumes:
  apis-snitzsh-main-rust:
    driver: local
  uis-snitzsh-main-vue:
    driver: local
Error: unexpected end of JSON input
