---
# Source: docker-compose/templates/main.yaml
name: apis
services:
  apis-snitzsh-main-fastify:
    build:
      args:
        _WORKDIR: /app
        RUST_APP_PLATFORM_CLUSTER_NAME: dev
        RUST_APP_PLATFORM_CLUSTER_TYPE: local
        RUST_APP_PLATFORM_HOST: 0.0.0.0
        RUST_APP_PLATFORM_PORT: "3000"
        RUST_APP_PLATFORM_SCRIPT_TARGET: dev
      context: ../../../apis/snitzsh/main-fastify
      dockerfile: Dockerfile
      target: dev-stage
    image: apis-snitzsh-main-fastify:latest
    platform: linux/arm64
  apis-snitzsh-main-rust:
    build:
      args:
        _WORKDIR: /app
        RUST_APP_PLATFORM_CLUSTER_NAME: dev
        RUST_APP_PLATFORM_CLUSTER_TYPE: local
        RUST_APP_PLATFORM_HOST: 0.0.0.0
        RUST_APP_PLATFORM_PORT: "3000"
        RUST_APP_PLATFORM_SCRIPT_TARGET: dev
      context: ../../../apis/snitzsh/main-rust
      dockerfile: Dockerfile
      target: dev-stage
    image: apis-snitzsh-main-rust:latest
    platform: linux/arm64
---
# Source: docker-compose/templates/main.yaml
name: cache-db-uis
services:
  cache-db-uis-snitzsh-redisinsight:
    image: redislabs/cache-db-uis:latest
    platform: linux/arm64
---
# Source: docker-compose/templates/main.yaml
name: cache-dbs
services:
  cache-dbs-snitzsh-redis:
    image: cache-dbs:latest
    platform: linux/arm64
---
# Source: docker-compose/templates/main.yaml
name: db-uis
services:
  db-uis-snitzsh-pgadmin4:
    image: dpage/db-uis:latest
    platform: linux/arm64
---
# Source: docker-compose/templates/main.yaml
name: dbs
services:
  dbs-snitzsh-postgres:
    image: dbs:latest
    platform: linux/arm64
---
# Source: docker-compose/templates/main.yaml
name: uis
services:
  uis-snitzsh-main-vue:
    build:
      args:
        _WORKDIR: /app
        VITE_APP_PLATFORM_CLUSTER_NAME: dev
        VITE_APP_PLATFORM_CLUSTER_TYPE: local
        VITE_APP_PLATFORM_HOST: 0.0.0.0
        VITE_APP_PLATFORM_PORT: "8080"
        VITE_APP_PLATFORM_SCRIPT_TARGET: dev
      context: ../../../uis/snitzsh/main-vue
      dockerfile: Dockerfile
      target: dev-stage
    image: uis-snitzsh-main-vue:latest
    platform: linux/arm64
