---
# Source: docker-compose/templates/main.yaml
version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB="snitch_db"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@snitch.com
      - PGADMIN_DEFAULT_PASSWORD=root
    expose:
      - '80'
    ports:
      - '5050:80'
    volumes:
      - ./volumes/pgadmin4:/var/lib/pgadmin
    links:
      - postgres
    depends_on:
      - postgres
  redis:
    container_name: redis
    image: redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes:
      - ./volumes/redis/data:/data
      # - ./redis/config:/user/local/etc/redis
  redisinsight:
    image: redislabs/redisinsight:latest
    expose:
      - "8001"
    ports:
      - '8001:8001'
    volumes:
      - ./volumes/redisinsight:/db
    links:
      - redis
    depends_on:
      - redis
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 9000:3000
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
volumes:
  postgres:
    driver: local
  redis:
    driver: local
  redisinsight:
    driver: local
  grafana:
    driver: local
