---
# Source: docker-compose/templates/main.yaml
version: "3.8"
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: snitzsh_db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - postgres
  pgadmin4:
    container_name: pgadmin4
    hostname: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@snitzsh.com
      PGADMIN_DEFAULT_PASSWORD: root
    expose:
      - '80'
    ports:
      - '5050:80'
    volumes:
      - ./volumes/pgadmin4:/var/lib/pgadmin
    networks:
      - postgres
    depends_on:
      - postgres
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    restart: always
    environment:
      REDIS_USERNAME: root
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    volumes:
      - ./volumes/redis/data:/data
    networks:
      - redis
  redisinsight:
    container_name: redisinsight
    hostname: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - ./volumes/redisinsight:/db
    networks:
      - redis
    depends_on:
      - redis
volumes:
  postgres:
    driver: local
  redis:
    driver: local
  redisinsight:
    driver: local
  grafana:
    driver: local
networks:
  redis:
    driver: bridge
  postgres:
    driver: bridge
