---
# Source: docker-compose/templates/main.yaml
name: global
services:
  scripts-global-machine_set_up-bash:
    build:
      args:
        _WORKDIR: /app
      context: ../../../scripts/global/machine_set_up-bash
      dockerfile: Dockerfile
      target: ubuntu-dev-stage
    container_name: scripts-global-machine_set_up-bash
    environment: {}
    hostname: scripts-global-machine_set_up-bash
    image: scripts-global-machine_set_up-bash:latest
    labels:
    - com.docker.compose.software-type=private
    - com.docker.compose.utility-type=scripts
    - com.docker.compose.app-name=global
    - com.docker.compose.project-name=machine_set_up-bash
    - com.docker.compose.service-name=scripts-global-machine_set_up-bash
    - com.docker.compose.platform=linux/amd64
    - com.docker.compose.docker-stage=ubuntu-dev-stage
    - com.docker.compose.target-script=dev
    platform: linux/amd64
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - ../../../scripts/global/machine_set_up-bash:/app
volumes:
  scripts-global-machine_set_up-bash:
    driver: local
networks:
  global:
    driver: bridge
