---
# Source: docker-compose/templates/main.yaml
name: platform
services:
  apis-snitzsh-main-rust:
    build:
      args:
        _WORKDIR: /app
        RUST_APP_PLATFORM_CLUSTER_NAME: dev
        RUST_APP_PLATFORM_CLUSTER_TYPE: local
        RUST_APP_PLATFORM_HOST: 0.0.0.0
        RUST_APP_PLATFORM_PORT: "3000"
        RUST_APP_PLATFORM_SCRIPT_TARGET: dev
      context: ../../../apis/snitzsh/main-rust
      dockerfile: Dockerfile
      target: dev-stage
    container_name: apis-snitzsh-main-rust
    depends_on: []
    environment: {}
    hostname: apis-snitzsh-main-rust
    image: apis-snitzsh-main-rust:latest
    labels:
    - com.docker.compose.software-type=private
    - com.docker.compose.component-name=apis
    - com.docker.compose.app-name=snitzsh
    - com.docker.compose.project-name=main-rust
    - com.docker.compose.service-name=apis-snitzsh-main-rust
    - com.docker.compose.platform=linux/arm64
    - com.docker.compose.docker-stage=dev-stage
    - com.docker.compose.target-script=dev
    networks:
    - platform
    platform: linux/arm64
    ports:
    - 3000:3000
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - ../../../apis/snitzsh/main-rust:/app
  cache-dbs-snitzsh-redis:
    command: redis-server --save 20 1 --loglevel warning --requirepass root
    container_name: cache-dbs-snitzsh-redis
    depends_on: []
    environment:
      REDIS_USERNAME: root
    expose:
    - "6379"
    hostname: cache-dbs-snitzsh-redis
    image: redis:latest
    labels:
    - com.docker.compose.software-type=public
    - com.docker.compose.component-name=cache-dbs
    - com.docker.compose.app-name=snitzsh
    - com.docker.compose.project-name=redis
    - com.docker.compose.service-name=cache-dbs-snitzsh-redis
    - com.docker.compose.platform=linux/arm64
    networks:
    - platform
    platform: linux/arm64
    ports:
    - 6379:6379
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - ./volumes/cache-dbs-snitzsh-redis/data:/data
  dbs-snitzsh-postgres:
    container_name: dbs-snitzsh-postgres
    depends_on: []
    environment:
      POSTGRES_DB: snitzsh_db
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    expose:
    - "5432"
    hostname: dbs-snitzsh-postgres
    image: postgres:latest
    labels:
    - com.docker.compose.software-type=public
    - com.docker.compose.component-name=dbs
    - com.docker.compose.app-name=snitzsh
    - com.docker.compose.project-name=postgres
    - com.docker.compose.service-name=dbs-snitzsh-postgres
    - com.docker.compose.platform=linux/arm64
    networks:
    - platform
    platform: linux/arm64
    ports:
    - 5432:5432
    restart: always
    stdin_open: true
    tty: true
    volumes:
    - ./volumes/dbs-snitzsh-postgres/data:/var/lib/postgresql/data
    - ./volumes/dbs-snitzsh-postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  apis-snitzsh-main-rust:
    driver: local
  cache-dbs-snitzsh-redis:
    driver: local
  dbs-snitzsh-postgres:
    driver: local
networks:
  platform:
    driver: bridge
