---
# Source: docker-compose/templates/main.yaml
version: "3.8"
services:
  apis:
    container_name: api-rust
    hostname: api-rust
    image: "api-rust"
    restart: "always"
    build:
      context: ../../../apis/snitzsh/main-rust
      dockerfile: "Dockerfile"
      target: dev-stage
      args:
        _WORKDIR: /app
        RUST_APP_PLATFORM_SCRIPT_TARGET: dev
        RUST_APP_PLATFORM_CLUSTER_NAME: dev
        RUST_APP_PLATFORM_CLUSTER_TYPE: local
        RUST_APP_PLATFORM_HOST: dev
        RUST_APP_PLATFORM_PORT: "3000"
    environment: {}
    volumes:
      - "../../../apis/snitzsh/main-rust:/app"
    labels:
      - "com.docker.compose.service=private"
      - "com.docker.compose.component-name=api-rust"
      - "com.docker.compose.component-type=apis"
    ports:
      - '3000:3000'
volumes:
  apis-fastify:
    driver: local
  apis-rust:
    driver: local
  grafana:
    driver: local
  pgadmin4:
    driver: local
  postgres:
    driver: local
  redis:
    driver: local
  redisinsight:
    driver: local
  main-vue:
    driver: local
networks:
  redis:
    driver: bridge
  postgres:
    driver: bridge
