# Default values for docker-compose.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

infrastructure_type: monolithic # microservice | monolithic
components:
  grafana: true
  postgres: true
  pgadmin4: true
  redis: true
  redisinsight: true
  apis_fastify: false # If microservice it will use `apis` property
  apis_rust: true
  website_vue: false

docker:
  volumes: true

# All Microservice API will be dynamically place here... if empty it will do `monolithic` build
front-end:
  customer-facing: true
  admin-portal: true

# Mainly for `local` development: redis, redisinsight, postgres, pgadmin4
auth:
  email: 'root@snitch.com'
  username: 'root'
  password: 'root'

apis:
  # - api_
