# Default values for docker-compose.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

infrastructure_type: monolithic # microservice | monolithic
components:
  postgres: true
  pgadmin4: true
  redis: true
  apis_fastify: true # If microservice it will use `apis` property
  website_vue: true

docker:
  volumes: true

# All Microservice API will be dynamically place here... if empty it will do `monolithic` build
front-end:
  customer-facing: true
  admin-portal: true

apis:
  # - api_
